services:
  sheet-folio:
    build: .
    volumes:
      - ./volumes/app:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "3444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../certs/volumes/data/sheet-folio:/etc/nginx/certs:ro
    depends_on:
      - sheet-folio
    restart: unless-stopped
